/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        current: "currentColor",
        transparent: "transparent",
        white: "#FFFFFF",
        black: "#1C2434",
        black2: "#010101",

        // Semantic brand tokens
        bg: "var(--color-bg)",
        surface: {
          DEFAULT: "var(--color-surface)",
          elevated: "var(--color-surface-elevated)",
          hover: "var(--color-surface-hover)",
        },
        sidebar: {
          bg: "var(--color-sidebar-bg)",
          text: {
            DEFAULT: "var(--color-sidebar-text)",
            active: "var(--color-sidebar-text-active)",
          },
          icon: "var(--color-sidebar-icon)",
          border: "var(--color-sidebar-border)",
        },
        border: {
          DEFAULT: "var(--color-border)",
          subtle: "var(--color-border-subtle)",
          strong: "var(--color-border-strong)",
        },
        text: {
          1: "var(--color-text-1)",
          2: "var(--color-text-2)",
          3: "var(--color-text-3)",
          4: "var(--color-text-4)",
        },
        primary: {
          DEFAULT: "var(--color-primary)",
          hover: "var(--color-primary-hover)",
          surface: "var(--color-primary-surface)",
          border: "var(--color-primary-border)",
        },
        success: "var(--color-success)",
        danger: "var(--color-danger)",
        warning: "var(--color-warning)",
        secondary: "var(--color-secondary)",

        // TailAdmin primitives still used by legacy components
        body: "#64748B",
        bodydark: "#AEB7C0",
        bodydark1: "#DEE4EE",
        bodydark2: "#8A99AF",
        stroke: "#E2E8F0",
        strokedark: "#2E3A47",
        boxdark: "#24303F",
        "boxdark-2": "#1A222C",
        gray: "#EFF4FB",
        graydark: "#333A48",
        gray2: "#F7F9FC",
        gray3: "#FAFAFA",
        whiten: "#F1F5F9",
        whiter: "#F5F7FD",
        "form-input": "#1D2A39",
        "form-strokedark": "#3D4D60",
        red: "#FB5454",
        meta: {
          1: "#DC3545",
          2: "#EFF2F7",
          3: "#10B981",
          4: "#313D4A",
          5: "#259AE6",
          6: "#FFBA00",
          7: "#FF6766",
          8: "#F0950C",
          9: "#E5E7EB",
          10: "#687B8B",
        },
      },
      borderRadius: {
        xs: "var(--radius-xs)",
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        "2xl": "var(--radius-2xl)",
        full: "var(--radius-full)",
      },
      spacing: {
        sidebar: "var(--sidebar-w)",
        "sidebar-collapsed": "var(--sidebar-w-collapsed)",
        topbar: "var(--topbar-h)",
      },
      fontSize: {
        xs: "var(--text-xs)",
        sm: "var(--text-sm)",
        base: "var(--text-base)",
        md: "var(--text-md)",
        lg: "var(--text-lg)",
        xl: "var(--text-xl)",
        "2xl": "var(--text-2xl)",
        "3xl": "var(--text-3xl)",
        "4xl": "var(--text-4xl)",
      },
      fontFamily: {
        sans: ["var(--font-sans)", "ui-sans-serif", "system-ui", "sans-serif"],
        mono: ["var(--font-mono)", "ui-monospace", "SFMono-Regular", "Menlo", "monospace"],
      },
      boxShadow: {
        1: "var(--shadow-1)",
        2: "var(--shadow-2)",
        3: "var(--shadow-3)",
        4: "var(--shadow-4)",
        5: "var(--shadow-5)",
        6: "var(--shadow-6)",
        7: "var(--shadow-7)",
        8: "var(--shadow-8)",
        9: "var(--shadow-9)",
        10: "var(--shadow-10)",
        11: "var(--shadow-11)",
        12: "var(--shadow-12)",
        13: "var(--shadow-13)",
        14: "var(--shadow-14)",
        DEFAULT: "var(--shadow-default)",
        card: "var(--shadow-card)",
        "card-2": "var(--shadow-card-2)",
        switcher: "var(--shadow-switcher)",
        "switch-1": "var(--shadow-switch-1)",
      },
      zIndex: {
        999: "999",
        9999: "9999",
      },
    },
  },
};
